### ISSUE TITLE
Team update - Jul 27, 2022

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#149]
This is a @Quansight-Labs/czi-a11y-grant team sync 🎉🎉🎉! This is a way for the Team Members to provide status reports on what they've been up to this week and request help and attention for things they are working on. This issue will be closed at the end of the day.

_Copy and paste the template below, and answer questions as you wish!_

<details>
<summary>Response Template</summary>

```md
**Thanks I'd like to give 🙌**
- So-and-so helped me out a lot with foo...

**Updates from last week :heavy_check_mark:**
- I worked towards deliverable: <link-to-deliverable>

**Challenges I faced and things I'd like assistance with 🙏**
- I had a hard time figuring out ...

**My availability for next week**
- I'll be off on foo day...

**Important items for discussion 💬**
- I have a question about goal <link-to-goal>
- Can @foo give a comment on issue #NN ?
- I opened #NN for discussion, please chime in
- I need to discuss foo
```

</details>

#### :mag: Needs Triage

_The [Needs Triage issues](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/labels/status%3A%20needs%20triage) require an initial assessment and labeling._

* [Rendered notebook UX fixes - Round 1](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/148)
* [Rendered notebook user testing - Round 2](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/147)
* [Rendered notebook user testing - Round 1](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/146)

### :dart: Project boards

Please make sure the boards reflect the current status of the project.

[Jupyter a11y grant project](https://github.com/orgs/Quansight-Labs/projects/5/views/5)

**Comment by steff456** [comment]
**Thanks I'd like to give 🙌**
- Everyone for giving me queues in how to start!

**Updates from last week :heavy_check_mark:**
- I worked towards setting my local dev environment
- i started checking some questions related to https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/133

**Challenges I faced and things I'd like assistance with 🙏**
- I had a hard time figuring out actual tasks to start working on 😅

**My availability for next week**
- I'll be here!

**Important items for discussion 💬**
- I created this spreadsheet (https://docs.google.com/spreadsheets/d/1yaWY--2zBi7KqPAnMMbJp_aVXFFT8sBDdci8UfpKjO4/edit?usp=sharing) with @isabela-pf to start creating audit tasks than later will convert in issues for the theming work

**Comment by isabela-pf** [comment]
**Thanks I'd like to give 🙌**
- @steff456's energy is lovely! I appreciate her drive to tackle a task.
- @gabalafou has been working to coordinate us all, and I appreciate the effort!
- I've heard positive feedback about @tonyfast's onboarding of our team members, so I want to give kudos there!

**Updates from last week :heavy_check_mark:**
- #146. STScI User testing outreach begins. We have the go ahead, so we're getting people scheduled, writing recording consent forms, scheduling a test run, and generally getting things finalized for the first round of tests.
- #133. Theme status. Still nothing much to report. I just barely got to start experimenting with some of the non-color changes, but I can't decide if it's better to try and iterate via the inspector even though my CSS knowledge is pretty basic and I may be slow.
- I've been really slow.

**Challenges I faced and things I'd like assistance with 🙏**
- @gabalafou suggested we discuss the [draft theming checklist](https://github.com/Quansight-Labs/accessibility/pull/9/commits/76965844bc0af393939856ef08ac40af57a1b361), but it could be in another meeting.
- Any feedback on the issues for STScI work (made per request)? Is this what was needed? #143,  #146,  #147, #148. 

**My availability for next week**
- I'll be out of office on July 29.

**Important items for discussion 💬**
- I think I don't have anything now. I hope this meeting helps be iron out everyone's current work in relation to each other.

**Comment by gabalafou** [comment]
**Thanks I'd like to give 🙌**
- Thanks to @isabela-pf for always showing up, asking good questions, leading calls in the Jupyter community. I'm not sure I could do it.
- Thanks to @steff456 for being flexible in scheduling calls and bringing good energy :)
 
**Updates from last week :heavy_check_mark:**
- Spent time pairing with Stephannie.
- Spent time reviewing and understanding Isabela's work curating/scoping theme extension work.

**Challenges I faced and things I'd like assistance with 🙏**
- I cannot adequately review/respond to [Isabela's theme work](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/133#issuecomment-1171823501) on my own. I think this is a whole-team thing.

**My availability for next week**
- Here

**Important items for discussion 💬**
- Review my priorities with team. I have a lot more time to work on the grant. This is for the next few weeks:
  - testing: the testing tasks I want to finish up, merging my work with Tony's
  - theme extension: wherever I can be helpful
  - implementing accessibility fixes (with accompanying tests) directly in JupyterLab (or Lumino)
  - helping to onboard Stephannie and Kulsoom
  - for later: pydata-sphinx-theme pa11y work
- Isabela's [accessible theme curation/scoping](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/133#issuecomment-1171823501)
- Tania, please repeat: what does a good github/workflow look like in your mind for jupyter-a11y-testing? compared against the workflow we have now:

```yml
name: a11y tests

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        name: Fetch all history for all tags and branches
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: install development dependencies
        run: python -m pip install -e .
      - name: list jupyter build tasks
        run: python -m jupyter_accessibility -i jupyterlab -- list
          
      - name: establish the runtime systems for the builds
        run: python -m jupyter_accessibility -i jupyterlab -- env
      - name: setup the development content for building
        run: python -m jupyter_accessibility -i jupyterlab -- setup
      - name: setup the testing environments
        run: python -m jupyter_accessibility -i jupyterlab -- test_setup
      - name: run tests against the build
        run: python -m jupyter_accessibility -i jupyterlab -- test
      - name: upload testing results
        uses: actions/upload-artifact@v3
        with:
          name: a11y-test-results
          path: |
            jupyter-ally-build/jupyter-axe/test-results/*.html
            jupyter-ally-build/jupyter-axe/test-results/**/*.html
            jupyter-ally-build/jupyter-axe/test-results/*.json
            jupyter-ally-build/jupyter-axe/test-results/**/*.json
```
